apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persist
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-007824d1b683b2f22.efs.ap-southeast-2.amazonaws.com
    path: "/"
